version: "3.8"

services:
    app:
        image: sukima_app:latest
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - conf.env
        ports:
            - "8000:8000"
        volumes:
            - ./:/sukima/
        command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:14-bullseye
        env_file:
            - conf.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
