name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Dependencies
      run: sudo apt install docker-compose
    - name: Set Up Docker Environment
      run: docker-compose up -d && docker run --network host appropriate/curl --retry 30 --retry-connrefused http://localhost:8000/ 
